TARGET = mainEx

# path to files
S_DIR = src
INC_DIR = $(S_DIR)/include

# your source files present in dirs
SRC = $(S_DIR)/main.c
SRC += $(S_DIR)/operation.c

# your custom header files
INCLUDES = $(INC_DIR)/operations.h

# object files from source
OBJ = $()


$(TARGET):
	$(SRC)


